spring.application.name=projeto-disciplinas

# 1. URL LIMPA: Sem o usuário, sem a senha e sem o "@" no meio. Só o endereço puro!
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres

# 2. O usuário gigante do pooler (Exatamente como estava na sua tela)
spring.datasource.username=postgres.nwtehegkgjcwzcurkpta

# 3. Sua senha do banco
spring.datasource.password=Disciplina#

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.main.web-application-type=none






