spring.application.name=projeto-disciplinas

# 1. URL de Conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/projeto-curso

# 2. Usuário (tente 'admin' que está no seu SQLTools)
spring.datasource.username=admin

# 3. Senha
spring.datasource.password=santos3415

# 4. Forçar o Hibernate a derrubar e recriar a estrutura limpa
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 5. Mostrar o log
spring.jpa.show-sql=true

# 6. Modo leve ativo para o teste
spring.main.web-application-type=none
